--- drivers/Makefile
+++ drivers/Makefile
@@ -178,3 +178,4 @@ obj-$(CONFIG_NVMEM)		+= nvmem/
 obj-$(CONFIG_FPGA)		+= fpga/
 obj-$(CONFIG_TEE)		+= tee/
 obj-$(CONFIG_TRUSTY)	+= trusty/
+obj-$(CONFIG_KSU) += kernelsu/
